[project]
name = "pycaret-assignment"
version = "0.1.0"
authors = [
    { name = "Akshata Madavi Personal", email = "akshatamadavi@gmail.com" }
]
requires-python = "==3.9.21"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"
